travis:
  secure:
    BINSTAR_TOKEN: SMS9kZMKsBcXiB2UylbX+/KF4nPcI/hi4FDkUuHFsTtwFIbr4MjwrJ5TEGAt/Dm7ib56OGQ5MkbIIspZwGTm2FOCZVGwpor1hkkJ67bMJTBKB6Ej3wesbim9d4mjkU0lo7WlhP5XVQepqAlDzwPOOlPPoiQrUaB/e/fKN6XTTyxmHYSLLsvqBqjJw3h51nxAAIg8zYokS+dV/MbKHRjs2OnadGSo7J/dqSKTRAf6hiMKMOm8zeu2GXAZMrb7X/W0BepxiAmkSMq4avaWblmIv/I9/EWjzrz+Zz/7WrUzLJ+Bc1S292Eb3JtUTCZAV183zztq+u4iyW7hP9AudavJPh5lC92lqh+C7yBxg7FIOqOlxexO9aq3vF5UA4DGrEGZ0BHWjc0cCgm4bYNpOU6As0AD1jkpTFN57/2PLIWhFaX+a+GfmUWW3BcX0DDnmATjlCrlKu5zatGAVZoFl+cQ9t2KRG8K3v4X3CLzawPGqn2YULagoRapWp0s7x/cgcEXVEJ2DBN8ssV0CpyTWE9Fl6VfRFpI+dMgbLR5qPCE2VJo64HniZsWacnNFKDC/U7u9RXxAOAm3Mt+FrFdykW8hKHl6e+KtA6URWNcDjf3GL1ZgWN4ml6ntx2UIVZIxHBuwYShNRrJTgCsiqCNq09h5fWM7LkqFHEojosJDzj0AdE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
conda_forge_output_validation: true
