travis:
  secure:
    BINSTAR_TOKEN: hdb3B2PpeeEZ0aRJOvI9OiEgoZljWsEUe1qkDOgy7UP/Pcgd97Vu2ann7MUnwvsPmBe1ALt+tAwkkIAhHsJ/E0mN1CzC8mRUKFoKG79naXM8L5UkayLVoj//XXYK/nscjzel4oHxiMAX6eD9hgbLdr/j4q+0N1z74ezmIfQFKOdwl9kWrr3r4OGuBeRT0CCnjbUmY7CfM3bDlRoTcJYAL1ulHCwn6WdXieIVwTmd6dEWSFLSKOgcsXf1KeBZfw7EWURff7yQGyhan5dJDybx300TlFxVXGcXbuecAg1g8gFfbvgq33F610CSqj8upTZc7ScGsUNXZNndNS3gFjeReGI0TAphjCA6cb2XI/ySCBKBa/sX8o8/x21ixbtTmCqC51n3e8C4wtjqL1vaJPaFhYPGw7gZh9REuEiS3hUMfhE+TUZijmbbn2Amg5ir4eaNPmZ6+fD2iPXLAn8porVW6oyDH5r8uBk9FZ9SIlWC5QPCE/+DKmQFrkCNtv2nA1dV1fSweC/G4u/TbFYIoZBJ01whOZJjfLy5rOg3DTAnxynfqZ3IIPioF3Qb+DEI4nyig6UvJzldQXS/Vquk4GibOhHrWHyE0a9AcPrkg3kOwVf0B5RmhIBdZ8VIBtlXcJ9ggGdT0L2TwuwSqgpipNzUu2saYizV3cWxyuTYx1H/uqY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
